-- Go Ranking Analysis schema. Applied on every startup; all statements are idempotent.

CREATE TABLE IF NOT EXISTS events (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  date        TEXT,                 -- ISO YYYY-MM-DD, NULL for the seeded Open rows
  source_hash TEXT UNIQUE,          -- sha256 of the uploaded file; NULL for seeded rows
  imported_at TEXT
);

-- Two always-present containers for individually-entered standalone games (future path).
INSERT INTO events (id, name) VALUES (1, 'Open (Ranked)'), (2, 'Open (Unranked)')
  ON CONFLICT (id) DO NOTHING;

-- Realign the identity sequence so importer-generated ids don't collide with the seed.
SELECT setval(pg_get_serial_sequence('events', 'id'), GREATEST((SELECT MAX(id) FROM events), 1));

CREATE TABLE IF NOT EXISTS players (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name    TEXT NOT NULL,        -- first-seen "First Last"
  normalized_name TEXT NOT NULL UNIQUE  -- trimmed + internal whitespace collapsed + lowercased
);

CREATE TABLE IF NOT EXISTS event_players (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id     INTEGER NOT NULL REFERENCES events(id),
  player_id    INTEGER REFERENCES players(id),  -- always set by the importer; remappable later
  og_key       TEXT NOT NULL,                   -- key used to reference this player in <Game>
  first_name   TEXT,
  last_name    TEXT,
  display_name TEXT NOT NULL,                   -- raw "First Last" from the file
  rank         TEXT,
  club         TEXT,
  country      TEXT,
  egf_pin      TEXT,
  UNIQUE (event_id, og_key)
);

CREATE INDEX IF NOT EXISTS idx_event_players_player_id ON event_players(player_id);
CREATE INDEX IF NOT EXISTS idx_event_players_event_id ON event_players(event_id);

CREATE TABLE IF NOT EXISTS games (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id               INTEGER NOT NULL REFERENCES events(id),
  round_number           INTEGER,
  white_event_player_id  INTEGER NOT NULL REFERENCES event_players(id),
  black_event_player_id  INTEGER REFERENCES event_players(id),   -- NULL for a bye
  winner_event_player_id INTEGER REFERENCES event_players(id),   -- white or black; NULL otherwise
  is_game                SMALLINT NOT NULL,                      -- 0/1
  result_type            TEXT NOT NULL,                          -- game|draw|forfeit|both_win|both_lose|bye|no_result
  result_raw             TEXT,
  handicap               INTEGER
);

CREATE INDEX IF NOT EXISTS idx_games_white ON games(white_event_player_id);
CREATE INDEX IF NOT EXISTS idx_games_black ON games(black_event_player_id);
CREATE INDEX IF NOT EXISTS idx_games_winner ON games(winner_event_player_id);
CREATE INDEX IF NOT EXISTS idx_games_event ON games(event_id);

-- Invite-only allowlist. The whole access-control mechanism: a Google-authenticated
-- visitor gets the full app iff their (lowercased) email has a row here. The owner
-- adds/removes invitees by editing rows directly (Neon console / psql). Seeded with
-- the owner's own email so the first sign-in isn't locked out.
CREATE TABLE IF NOT EXISTS allowed_emails (
  email    TEXT PRIMARY KEY,   -- lowercased
  added_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO allowed_emails (email) VALUES ('evozong@gmail.com')
  ON CONFLICT (email) DO NOTHING;
